export const LIST_MOVIE_SCHEDULE_SUCCESS = "listMovieReducer/LIST_MOVIE_SCHEDULE_SUCCESS";
export const LIST_MOVIE_SCHEDULE_REQUEST = "listMovieReducer/LIST_MOVIE_SCHEDULE_REQUEST";
export const LIST_MOVIE_SCHEDULE_FAILED = "listMovieReducer/LIST_MOVIE_SCHEDULE_FAILED";